# Spectral Graph Theory - Chapter 5

In [1]:
import numpy as np

In [2]:
def get_laplacian(M):
    x, _ = M.shape
    d = M.dot(np.ones(x))
    L = np.eye(x) - (1/d) * M
    return L

In [3]:
def get_laplacian_eig(M):
    L = get_laplacian(M)
    return np.linalg.eig(L)

In [4]:
def get_eig(M):
    return np.linalg.eig(M)

λ<sub>2</sub>(K<sub>n</sub>) = n

In [13]:
M = np.array([[0,1,0,1],[1,0,1,0],[0,1,0,1],[1,0,1,0]])

In [14]:
eigvals, eigvecs = get_eig(M)
sorted(eigvals, reverse=True)

[1.9999999999999993, 0.0, 0.0, -1.999999999999999]

In [15]:
eigvals, eigvecs = get_laplacian_eig(M)
sorted(eigvals)

[-2.220446049250313e-16, 1.0, 1.0, 1.9999999999999993]

In [16]:
eigvals, eigvecs

(array([-2.22044605e-16,  2.00000000e+00,  1.00000000e+00,  1.00000000e+00]),
 array([[ 5.00000000e-01,  5.00000000e-01,  5.97434869e-09,
         -7.05097831e-01],
        [ 5.00000000e-01, -5.00000000e-01, -7.07106781e-01,
          5.32639505e-02],
        [ 5.00000000e-01,  5.00000000e-01, -5.97434837e-09,
          7.05097831e-01],
        [ 5.00000000e-01, -5.00000000e-01,  7.07106781e-01,
         -5.32639505e-02]]))

<b>disconnected graph</b>

In [9]:
M = np.array([[0,1,0,0],[1,0,0,0],[0,0,0,1],[0,0,1,0]])

In [10]:
get_laplacian(M)

array([[ 1., -1.,  0.,  0.],
       [-1.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -1.],
       [ 0.,  0., -1.,  1.]])

In [11]:
get_laplacian_eig(M)

(array([2., 0., 2., 0.]),
 array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
        [-0.70710678,  0.70710678,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.70710678,  0.70710678],
        [ 0.        ,  0.        , -0.70710678,  0.70710678]]))

In [18]:
eigvecs[:,1], eigvals[1]

(array([ 0.5, -0.5,  0.5, -0.5]), 1.9999999999999993)

In [22]:
for i in range(4):
    print(M.dot(eigvecs[:,i]), eigvecs[:,i] * eigvals[i])

[1. 1. 1. 1.] [-1.11022302e-16 -1.11022302e-16 -1.11022302e-16 -1.11022302e-16]
[-1.  1. -1.  1.] [ 1. -1.  1. -1.]
[1.11022302e-16 3.14018490e-16 1.11022302e-16 3.14018490e-16] [ 5.97434869e-09 -7.07106781e-01 -5.97434837e-09  7.07106781e-01]
[7.63278329e-17 2.22044605e-16 7.63278329e-17 2.22044605e-16] [-0.70509783  0.05326395  0.70509783 -0.05326395]
