In [1]:
import numpy as np
import pandas as pd

In [2]:
# state 0 lose, state 9 win
states = 10
actions = 2
reward = -1
alfa = 1
win = 100
lose = -100
world = np.zeros((states, actions))
world[9,1] = win
world[0,0] = lose
world

array([[-100.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,  100.]])

In [3]:
s = np.random.randint(10)
a = np.random.randint(2)
s , a

(4, 1)

In [4]:
s = 8
a = 1

In [5]:
for i in range(1000):
    # update value function
    if s>=0 and s<9:
        world[s,1] = reward + max(world[s+1])
    if s<=9 and s>0:
        world[s,0] = reward + max(world[s-1])

    # act greedy with random
    
    coin = np.random.randint(2)
    coin = 0
    if coin == 1:
        a = np.argmax(world[s])
    else:
        a = np.random.randint(2)
   
    if a==0 and s>0:
        s-=1
    elif a==1 and s<9:
        s+=1
world

array([[-100.,   91.],
       [  90.,   92.],
       [  91.,   93.],
       [  92.,   94.],
       [  93.,   95.],
       [  94.,   96.],
       [  95.,   97.],
       [  96.,   98.],
       [  97.,   99.],
       [  98.,  100.]])

In [6]:
s

9

In [7]:
    if s>=0 and s<9:
        world[s,1] = reward + max(world[s+1])
    if s<=9 and s>0:
        world[s,0] = reward + max(world[s-1])

    # act greedy with random

    coin = np.random.randint(2)
    if coin == 1:
        a = np.argmax(world[s])
    else:
        a = np.random.randint(2)
        
    if a==0 and s>0:
        s-=1
    elif a==1 and s<9:
        s+=1
s,a

(9, 1)

In [8]:
world

array([[-100.,   91.],
       [  90.,   92.],
       [  91.,   93.],
       [  92.,   94.],
       [  93.,   95.],
       [  94.,   96.],
       [  95.,   97.],
       [  96.,   98.],
       [  97.,   99.],
       [  98.,  100.]])

In [9]:
s , a

(9, 1)